# Page Rank

In [1]:
import numpy as np

## Given: the adjacency matrix

In [2]:
adjacency_matrix = np.asarray([[1, 0, 1, 0, 1],
                              [0, 0, 0, 1, 1],
                              [1, 0, 0, 0, 1],
                              [0, 0, 0, 1, 1],
                              [1, 0, 0, 0, 0]], dtype=int)
adjacency_matrix

array([[1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0]])

## Calculate in-degree and out-degree for every node

In [4]:
def deg_Calc(adjMatrix):
    """
    Arguments:
        adjMatrix - the adjacency matrix of type numpy.ndarray
    Result:
       It returns dictionary with nodes n1,... as keys and as values it keeps list of out-degree and in-degree (in this order).  
    """
    if adjMatrix.shape[0] != adjMatrix.shape[1]:
        raise Exception('Adjacency matrix should be a square matrix!')
        
    n = adjMatrix.shape[0]           
    result = dict.fromkeys(['n' + str(i+1) for i in range(n)])
  
    for i in range(n):
        result['n' + str(i+1)] = [sum(adjMatrix[i,:]),sum(adjMatrix[:, i])]
  
    return result

In [5]:
deg_Calc(adjacency_matrix)

{'n1': [3, 3], 'n2': [2, 0], 'n3': [2, 1], 'n4': [2, 2], 'n5': [1, 4]}

## Generate a Stochastic Transition Matrix (STM) for a page-rank random walk over the graph from the given adjacency matrix. Consider probability of teleport alpha = 0,1.

In [6]:
def stm_Calc(adjMatrix, alpha=0.1):
  
    if adjMatrix.shape[0] != adjMatrix.shape[1]:
        raise Exception('Adjacency matrix should be a square matrix!') 
  
    result = np.ndarray(dtype=float, shape=adjMatrix.shape)
    n = adjMatrix.shape[0]
  
    for i in range(n):
        for j in range(n):
            out_degree = sum(adjMatrix[i])
            if out_degree == 0:
                result[i, j] = 1 / n
            elif adjMatrix[i, j] == 0:
                result[i, j] = alpha / n
            else:
                result[i, j] = alpha / n + (1 - alpha)/out_degree
        
    return result

In [7]:
stm_Calc(adjacency_matrix)

array([[0.32, 0.02, 0.32, 0.02, 0.32],
       [0.02, 0.02, 0.02, 0.47, 0.47],
       [0.47, 0.02, 0.02, 0.02, 0.47],
       [0.02, 0.02, 0.02, 0.47, 0.47],
       [0.92, 0.02, 0.02, 0.02, 0.02]])

## Compute page rank

In [8]:
def rank_Calc(stMatrix, iterNum=5):
    """
    Arguments:
        stMatrix - a Stochastic Transition Matrix
        iterNum - defines after how many times/iterations can we see the page ranks
    Result:
        Page rank values.
    """ 
    n = stMatrix.shape[0]
    x = np.array([1/n]*n)

    for i in range(iterNum):
        x = np.dot(x, stMatrix)

    return x

In [9]:
rank_Calc(stm_Calc(adjacency_matrix))

array([0.4827365 , 0.02      , 0.1647845 , 0.05876638, 0.27371263])